name: Build and Publish Broadcast-Channel

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the develop branch
  push:
    branches: [master]

env:
    DESIRED_NODE_VERSION: 20
    DESIRED_PNPM_VERSION: "8.6.2"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    concurrency: build-and-deploy
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.DESIRED_NODE_VERSION }}

      - name: Install npm dependencies
        run: |
          npm ci --production=false

      - name: Run build
        run: npm run build

      - uses: actions/setup-node@v3
        with:
          registry-url: 'https://registry.npmjs.org'

      # NOTE:
      # By default NPM access tokens expire after a year, and so these will need to be updated when the build starts to fail.
      - name: Publish
        run: npm publish --access=public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
